Metrics/AbcSize:
  Max: 18
  # メソッドのABCサイズの最大許容値を18に設定します。ABCサイズは、メソッドの複雑さを測定する指標です。
  # sessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。

Metrics/CyclomaticComplexity:
  Max: 9
  # メソッドの循環的複雑度の最大許容値を9に設定します。循環的複雑度は、コードの分岐点の数を測定する指標です。
  # これもsessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。

Metrics/PerceivedComplexity:
  Max: 11
  # メソッドの認知的複雑度の最大許容値を11に設定します。認知的複雑度は、人間がコードを理解するのに必要な労力の尺度です。
  # これもsessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。
  # あとはsessions_controller.rbのcreateアクションの修正。

Rails/HelperInstanceVariable:
  Exclude:
    - 'app/helpers/sessions_helper.rb'
  # ヘルパー内のインスタンス変数の使用に関するRailsの規約から特定のヘルパーファイルを除外します。
  # これもsessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。


Rails/I18nLocaleTexts:
  Exclude:
    # - 'app/controllers/account_activations_controller.rb'
    # - 'app/controllers/application_controller.rb'
    # - 'app/controllers/microposts_controller.rb'
    # - 'app/controllers/password_resets_controller.rb'
    # - 'app/controllers/sessions_controller.rb'
    # - 'app/controllers/users_controller.rb'
    # - 'app/mailers/user_mailer.rb'
    # - 'app/models/micropost.rb'
  # I18nのロケールテキストに関するRailsの規約から特定のファイルを除外します。

Rails/InverseOf:
  Exclude:
    - 'app/models/user.rb'
  # belongs_to関連における`:inverse_of`の使用に関するRailsの規約から特定のモデルファイルを除外します。
Rails/RedundantPresenceValidationOnBelongsTo:
  Exclude:
    - 'app/models/micropost.rb'
    - 'app/models/relationship.rb'
  # belongs_to関連における不要なpresence: true検証を除外する。これらのモデルでは特定の理由でpresence: trueが必要。

Rails/SkipsModelValidations:
  Exclude:
    - 'app/models/user.rb'
  # モデル検証をスキップするメソッドの使用を許可するファイルを指定。これらのファイルでは検証をスキップする操作が必要。

Style/CommentedKeyword:
  Exclude:
    - 'app/helpers/sessions_helper.rb'
  # コメントされたキーワードの使用を許可するファイルを指定。sessions_helperでは特定の理由でコメントを使用。

Style/GlobalStdStream:
  Exclude:
    - 'spec/rails_helper.rb'
  # 標準出力や標準エラー出力のグローバル変数の使用を許可するファイルを指定。rails_helperではログ出力などで必要。

Style/SafeNavigation:
  Exclude:
    - 'app/controllers/password_resets_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/helpers/sessions_helper.rb'
  # セーフナビゲーション演算子の使用を許可するファイルを指定。これらのファイルではnilチェックを簡潔に行うために使用。

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
  # 特殊なグローバル変数の使用に関して、Perlスタイルの命名を推奨する。

Style/StringConcatenation:
  Exclude:
    - 'minitest/models/user_test.rb'
  # 文字列の連結に関する規約から特定のテストファイルを除外。user_testでは文字列連結がテストの要件になっている。

Layout/LineLength:
  Max: 198
  # 1行あたりの最大文字数を198文字に設定。これにより、特定の長い行が許可される。
