# メソッドの循環的複雑度の最大許容値を9に設定。
Metrics/CyclomaticComplexity:
  Max: 9
  # sessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。

# メソッドの認知的複雑度の最大許容値を11に設定。
Metrics/PerceivedComplexity:
  Max: 11
  # sessions_helper.rbのcurrent_userメソッドを修正することでおそらく改善できる。
  # あとはsessions_controller.rbのcreateアクションの修正。

# models/relationship.rbでのpresence: true検証を除外。
Rails/RedundantPresenceValidationOnBelongsTo:
  Exclude:
    - 'app/models/relationship.rb'
  # models/relationship.rbでpresence: true検証を除外するとrubocopをパスするが、
  # 今度はrelationship_specのfollowerd_idが存在しない時のテストと、follower_idが存在しない時の
  # テストが失敗する。バリデーションを行うタイミングが変わるから・・・？
