version: '3'

services: 
    db:
        image: mysql:8.0.36
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./db/mysql/volumes:/var/lib/mysql
        environment: 
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"
    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - db
       