default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db


development:
  <<: *default
  database: tsunarhythm_development

test:
  <<: *default
  database: tsunarhythm_test

production:
  <<: *default
  database: <%= ENV['MYSQL_NAME'] %>
  username: myuser
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>