default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db


development:
  <<: *default
  database: tsunarhythm_development

test:
  <<: *default
  database: tsunarhythm_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  socket: <%= ENV['DB_SOCKET'] %>
  host: <%= ENV['DB_HOST'] %>